version: '3.1'

services:
  db:
    image: postgres:10.9-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: